#!/bin/bash

# run jflex
java -jar ../../bin/jflex-1.6.1.jar --nobak -d src src/Lexer.flex

# compile source into bin directory
javac -d bin src/*.java

if [ $# -eq 0 ]; then
    # run all tests

    for i in {1..6}; do
        # java -cp bin Program test/test$i.minc
        echo "File: test$i"
        diff -yZqs --suppress-common-lines <(java -cp bin Program test/test$i.minc) test/solu$i.txt
    done;


    echo "File: testprepros"
    diff -yZqs --suppress-common-lines <(java -cp bin Program test/testprepros.minc) test/soluprepros.txt
else
    # run Program entrypoint using given test name
    # java -cp bin Program test/test$1.minc
    diff --color=always -Z <(java -cp bin Program test/$1.minc) test/output_$1.txt
fi


# diff
# for i in {0..8}; do
#     result = ${java -cp bin Program "test$i"}
#     solution = "test/testsolu$i.txt"
#     diff --color=always --width=80 -yw --suppress-common-lines <($result) $solution
# done;