#!/bin/bash

# clear console
clear

# run jflex
java -jar ../../bin/jflex-1.6.1.jar --nobak -d src src/Lexer.flex

# run Byacc/J
yacc -Jthrows="Exception" -Jextends=ParserImpl -Jclass=Parser -Jnorun -J src/Parser.y
mv Parser*.java src/

if [[ $1 = "-c" ]]; then
    exit 0
fi

# compile source into bin directory
javac -d bin src/*.java

if [[ $# -eq 0 ]]; then
    # run all tests

    for f in test/minc/*; do
        if [[ $f == *.minc ]];
        then
            # java -cp bin SemanticChecker test/test$i.minc
            # echo "File: $f"
            res=$(diff -yZqs --suppress-common-lines <(java -cp bin SemanticChecker $f) test/output/output_$(basename ${f%.*}).txt)
            
            case $res in
                *identical ) echo -e "\e[32m\u2714 $f\e[0m";;
                *differ    ) echo -e "\e[31m\u274c $f\e[0m";;
            esac
            # echo ">>> $f"
            # java -cp bin SemanticChecker $f
        fi
    done;
    unset res
else
    # run SemanticChecker entrypoint using given test name
    # java -cp bin SemanticChecker test/test$1.minc
    diff --color=always -Z <(java -cp bin SemanticChecker test/minc/$1.minc) test/output/output_$1.txt
fi


# diff
# for i in {0..8}; do
#     result = ${java -cp bin SemanticChecker "test$i"}
#     solution = "test/testsolu$i.txt"
#     diff --color=always --width=80 -yw --suppress-common-lines <($result) $solution
# done;